import Head from "next/head";
import { ChannelRow } from "./ChannelRow";

export const NetworkHomePage = () => {
  return (
    <>
      <Head>
        <title>Stream Thing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChannelRow />
      <ChannelRow />
      <ChannelRow />
      <ChannelRow />
      <ChannelRow />
    </>
  );
};
